baseURL = "https://laszlosomogyimusic.com/"
languageCode = "en-gb"
title = "Laszlo Somogyi Music"
theme="mainroad"

[Author]
    name="Laszlo Somogyi"
    bio="I'm a bass player. I play bom bom bom."

[Params]
    description="Laszlo Somogyi bass player and mixer"

